from enum import Enum


class Genres(Enum):
    MADNESS = "Безумие"
    MARTIAL_ARTS = "Боевые искусства"
    VAMPIRES = "Вампиры"
    MILITARY = "Военное"
    HAREM = "Гарем"
    DEMONS = "Демоны"
    DETECTIVE = "Детектив"
    CHILDREN = "Детское"
    JOSEI = "Дзёсэй"
    DRAMA = "Драма"
    GAMES = "Игры"
    HISTORICAL = "Исторический"
    ISEKAI = "Исэкай"
    COMEDY = "Комедия"
    SPACE = "Космос"
    MAGIC = "Магия"
    CARS = "Машины"
    МEXA = "Меха"
    MUSIC = "Музыка"
    PARODY = "Пародия"
    EVERYDAY_LIFE = "Повседневность"
    POLICE = "Полиция"
    ADVENTURES = "Приключения"
    PSYCHOLOGICAL = "Психологическое"
    ROMANCE = "Романтика"
    SAMURAI = "Самураи"
    SUPERNATURAL = "Сверхъестественное"
    SHOUJO = "Сёдзё"
    SHOUNEN = "Сёнэн"
    SPORT = "Спорт"
    SUPER_POWER = "Супер сила"
    SEINEN = "Сэйнэн"
    THRILLER = "Триллер"
    HORRORS = "Ужасы"
    FANTASY = "Фэнтези"
    SCHOOL = "Школа"
    ACTION = "Экшен"
    ETTY = "Этти"
